<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>RelativeIllumination.IO</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RelativeIllumination.Core\RelativeIllumination.Core.csproj" />
  </ItemGroup>
</Project>
